### ISSUE TITLE
movingmnist_iterator.py: error: too few arguments

### ISSUE THREAD

**Issue by seyoungleecho** [sxjscience/HKO-7#1]
I tried to run python3 nowcasting/movingmnist_iterator.py  as given in the Readme file, but it throwed back an exception below

usage: movingmnist_iterator.py [-h] [--no-distractors] {save,load} ...
movingmnist_iterator.py: error: too few arguments 

Kindly suggest how to go forward

**Comment by sxjscience** [comment]
@seyoungleecho Could you post the whole message? The reason may be that the arg-parser are not set correctly. You can try to check if the python version is larger than 3.5 or follow the listed instructions.

**Comment by seyoungleecho** [comment]
Thanks for giving solution... Mistake was i was using python2.7 rather than python3.5.  Problem solved. closing the issue
