### ISSUE TITLE
Inconsistent input and output

### ISSUE THREAD

**Issue by chencodeX** [sxjscience/HKO-7#2]
i try use your config to build a model.
but when my input data shape is (num_seqs,batch_szie,channels =3,H_size=256,W_size=256),the encoder last rnn out data shape is (num_seqs,batch_szie,channels =64,H_size=5,W_size=5).

and when i try generate a data like (num_seqs,batch_szie,channels =64,H_size=5,W_size=5) ,and put into a Forecaster , the Forecaster output shape is (num_seqs,batch_szie,channels =1,H_size=100,W_size=100)

My focus is on the H_size and W_sizeof the data。

Is this situation normal?

**Comment by sxjscience** [comment]
I see. We need to revise the kernel/padding/stride in the downsampling/upsampling layers in order to run it with different input shapes.

**Comment by sxjscience** [comment]
Could you show me the detailed config file for running the model?

**Comment by chencodeX** [comment]
i wil show you my model structure
Encoder (
  (conv1_act): Sequential (
    (0): Conv2d(2, 8, kernel_size=(7, 7), stride=(5, 5), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
  (rnn1_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(40, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(40, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn1_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (downsample1): Sequential (
    (0): Conv2d(32, 64, kernel_size=(5, 5), stride=(3, 3), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
  (rnn2_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn2_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn2_3): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (downsample2): Sequential (
    (0): Conv2d(64, 64, kernel_size=(5, 5), stride=(3, 3), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
  (rnn3_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn3_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn3_3): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
)
the encoder input shape is (8L, 2L, 256L, 256L),output shape is (8L, 64L, 5L, 5L)



Forecaster (
  (rnn1_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn1_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn1_3): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (upsample1): Sequential (
    (0): ConvTranspose2d(64, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
  (rnn2_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn2_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn2_3): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (upsample2): Sequential (
    (0): ConvTranspose2d(64, 64, kernel_size=(5, 5), stride=(3, 3), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
  (rnn3_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(96, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(96, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn3_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (deconv1): Sequential (
    (0): ConvTranspose2d(32, 8, kernel_size=(7, 7), stride=(5, 5), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
  (conv_final): Sequential (
    (0): Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
  (conv_pre): Conv2d(8, 1, kernel_size=(1, 1), stride=(1, 1))
)
the forecaster input shape is (8L, 64L, 5L, 5L), output shape is (8L, 1L, 100L, 100L).


i use pytorch,but my downsampling/upsampling layers is use the current configuration file in your code。

**Comment by chencodeX** [comment]
By the way, can I use Chinese to communicate with you?

**Comment by sxjscience** [comment]
@chencodeX 嗯，可以用中文。我看了一下应该可以缩放回256 * 256的，要不试试看改变forecaster的两个upsampling layer的stride? 理论上ConvGRU是不会改变height/width的，改变的只有upsampling/downsampling layer。可以把中间的shape打出来看一下。

**Comment by chencodeX** [comment]
对的，ConvGRU不会影响H和W。稍等我打印一下shape。

**Comment by chencodeX** [comment]
我将每一个模块处理后的数据shape 都在模块对应的部分写出来了。格式为（B,C,H,W）

Encoder (
data shape = (8L, 2L, 256L, 256L)
  (conv1_act): Sequential (
    (0): Conv2d(2, 8, kernel_size=(7, 7), stride=(5, 5), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
data shape = (8L, 8L, 51L, 51L)

  (rnn1_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(40, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(40, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn1_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
data shape = (8L, 32L, 51L, 51L)

  (downsample1): Sequential (
    (0): Conv2d(32, 64, kernel_size=(5, 5), stride=(3, 3), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
data shape =(8L, 64L, 17L, 17L)

  (rnn2_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn2_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn2_3): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
data shape = (8L, 64L, 17L, 17L)

  (downsample2): Sequential (
    (0): Conv2d(64, 64, kernel_size=(5, 5), stride=(3, 3), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
data shape = (8L, 64L, 5L, 5L)

  (rnn3_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn3_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn3_3): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
data shape = (8L, 64L, 5L, 5L)

)

接下来是forecaster
Forecaster (
data shape = (8L, 64L, 5L, 5L)

  (rnn1_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn1_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn1_3): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
data shape = (8L, 64L, 5L, 5L)

  (upsample1): Sequential (
    (0): ConvTranspose2d(64, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
data shape  =(8L, 64L, 10L, 10L)

  (rnn2_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn2_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn2_3): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
datashape = (8L, 64L, 10L, 10L)

  (upsample2): Sequential (
    (0): ConvTranspose2d(64, 64, kernel_size=(5, 5), stride=(3, 3), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
data shape = (8L, 64L, 20L, 20L)

  (rnn3_1): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(96, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(96, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (rnn3_2): ConvGRUCell (
    (dropout): Dropout (p = 0.5)
    (ConvGates): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (Conv_ct): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
data shape = (8L, 32L, 20L, 20L)

  (deconv1): Sequential (
    (0): ConvTranspose2d(32, 8, kernel_size=(7, 7), stride=(5, 5), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
data shape = (8L, 8L, 100L, 100L)

  (conv_final): Sequential (
    (0): Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): LeakyReLU (0.2)
  )
data shape = (8L, 8L, 100L, 100L)

  (conv_pre): Conv2d(8, 1, kernel_size=(1, 1), stride=(1, 1))
)
data shape = (8L, 1L, 100L, 100L)

您可以直接看每层内部的参数，我是否弄错了什么。

**Comment by sxjscience** [comment]
现在这个structure, Downsample的两个layer的stride分别是2, 3。upsample的两个layer的stride应该对应为3，2。现在似乎是2, 3。

**Comment by chencodeX** [comment]
他们对应的kernel_size呢？

**Comment by sxjscience** [comment]
我看到了，现在的网络是(5,3,1), (5,3,1)那么upsample应该也是(5,3, 1), (5, 3, 1)。kernel_size可能还得调一下，只要确保stride能对上就行了，就不会差这么多。

**Comment by chencodeX** [comment]
我改成同样的(5,3,1), (5,3,1)之后，forecaster的输出变成了225.还有什么方法来调整这个差异吗

**Comment by sxjscience** [comment]
比如把downsample的kernel_size调小，改成(4,3,1), (4,3,1)或者之类的。还有就是现在encoder的conv1_act是（7， 5，1)，forecaster的deconv1也是(7, 5, 1)，这两个也是可以调节的

**Comment by chencodeX** [comment]
嗯，明白了，主要就是要保证encoder和forecaster之间每层RNN的数据大小保持一致。

**Comment by chencodeX** [comment]
您一开始采用的输入是多少呢?
