### ISSUE TITLE
关于运行中存的在问题

### ISSUE THREAD

**Issue by kanon7** [sxjscience/HKO-7#4]
您好，最近在雷锋网看到你的文章，找到这里学习代码。我是初学者，在运行过程遇到以下问题，麻烦你有空解答下： 
1.我在Anaconda Prompt和cmd命令框中运行pip3 install develop均报错，提示找不到develop包，用pip search也没找到该包。报错语句：Could not find a version that satisfies the requirement develop (from versions: )             No matching distribution found for develop。
2.运行movingmnist_iterator.py，需要导入cv2模块，不知道在哪下载CV2模块。

**Comment by sxjscience** [comment]
@kanon7 
1. 可以使用 `python setup.py develop --user` or `python setup.py develop`.
2. 需要下载opencv-python，可以用pip install opencv-python
