### ISSUE TITLE
GPU memory and the speed of TrajGRU

### ISSUE THREAD

**Issue by cunwang-root** [sxjscience/HKO-7#6]
1. Could you talk more about the experiment settings especially the GPU memory required?

2. I implement TrajGRU in tensorflow and I notice that it runs much slower than ConvGRU. Do you have similar situation?

**Comment by sxjscience** [comment]
Yes, it will be slower and cost more GPU memory if you implement it using the same approach as in this repo. One solution to accelerate the speed and reduce the memory cost is to write your own kernel which combines "k warp" + "concat" + "conv1x1".

**Comment by cunwang-root** [comment]
Then could you tell me how much memory is required in your implementation? I can only run a single layer of TrajGRU with 9 links on sequence with total length 16  on a GeForce GTX 1080 Ti GPU (11 GB), it will run out of memory if I try with larger links. I'm not sure if it's the  problem of my implementation  or TrajGRU requires such much memory.

**Comment by sxjscience** [comment]
I use a single GTX1080 (no Ti) to do the MNIST++ experiment and use two GTX1080s to do the HKO7 experiment.
