### ISSUE TITLE
关于hko数据mask的问题

### ISSUE THREAD

**Issue by LittleDonkey1203** [sxjscience/HKO-7#7]
mask的输入是您论文里提到的2step吗？1.过滤雷达值，马氏距离异常的情况；2.通过clutter（outlier location）以及超出距离的情况吗？
另外，mask怎么给呢？0/1，true/false，0/255？

**Comment by sxjscience** [comment]
Yes, the masks are generated according to the way described in the paper. Also, they are 0-1 masks.
